# Generated by Django 2.1.2 on 2018-11-18 22:53

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Article',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('article_title', models.CharField(max_length=200, verbose_name='Заголовок')),
                ('article_text', models.TextField(verbose_name='Текст статьи')),
                ('article_image', models.ImageField(blank=True, upload_to='article', verbose_name='Изображение')),
                ('article_created', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата создания')),
                ('article_updated', models.DateTimeField(default=django.utils.timezone.now, verbose_name='Дата изменения')),
                ('article_reputation', models.IntegerField(default=0, verbose_name='Актуальность')),
                ('article_moderation', models.BooleanField(default=False, verbose_name='Модерация')),
            ],
            options={
                'verbose_name': 'Статья',
                'verbose_name_plural': 'Статьи',
                'ordering': ['article_updated'],
            },
        ),
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField()),
                ('comment_article', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article')),
            ],
        ),
    ]
