# Generated by Django 2.1.2 on 2018-11-18 23:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='comment_article',
        ),
        migrations.AlterModelTable(
            name='article',
            table='Article',
        ),
        migrations.DeleteModel(
            name='Comment',
        ),
    ]
