# Generated by Django 2.1.2 on 2018-11-18 23:20

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0003_remove_article_article_image'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_image',
            field=models.ImageField(blank=True, upload_to='article', verbose_name='Изображение'),
        ),
    ]
