# Generated by Django 2.1.2 on 2018-11-21 19:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0006_article_article_written_by'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_description',
            field=models.CharField(blank=True, max_length=100, verbose_name='Описание'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_keywords',
            field=models.CharField(blank=True, max_length=50, verbose_name='Ключевые слова'),
        ),
        migrations.AddField(
            model_name='article',
            name='article_submission',
            field=models.CharField(blank=True, max_length=350, verbose_name='Краткое изложение'),
        ),
    ]
