# Generated by Django 2.1.2 on 2018-11-21 19:21

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0007_auto_20181121_2213'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_description',
            field=models.CharField(max_length=100, verbose_name='Описание'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_keywords',
            field=models.CharField(max_length=50, verbose_name='Ключевые слова'),
        ),
        migrations.AlterField(
            model_name='article',
            name='article_submission',
            field=models.CharField(max_length=350, verbose_name='Краткое изложение'),
        ),
    ]
