# Generated by Django 2.1.2 on 2018-11-21 19:57

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0009_auto_20181121_2247'),
    ]

    operations = [
        migrations.AddField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
            preserve_default=False,
        ),
    ]
