# Generated by Django 2.1.2 on 2018-11-21 20:00

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0010_article_article_category'),
    ]

    operations = [
        migrations.AlterField(
            model_name='article',
            name='article_category',
            field=models.ForeignKey(blank=True, on_delete=django.db.models.deletion.CASCADE, to='article.Category'),
        ),
    ]
