# Generated by Django 2.1.2 on 2018-11-22 16:26

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0013_auto_20181121_2319'),
    ]

    operations = [
        migrations.RenameField(
            model_name='article',
            old_name='article_tegs',
            new_name='article_tags',
        ),
    ]
