# Generated by Django 2.1.2 on 2018-11-22 19:53

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('article', '0014_auto_20181122_1926'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comment',
            name='commented_by_user',
        ),
        migrations.AddField(
            model_name='comment',
            name='comment_written_by',
            field=models.ForeignKey(default=1, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор'),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name='comment',
            name='comment_article',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='article.Article', verbose_name='Статья'),
        ),
    ]
