# Generated by Django 2.1.2 on 2018-11-22 21:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0015_auto_20181122_2253'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comment',
            name='comment_moderation',
            field=models.BooleanField(default=False, verbose_name='Модерация'),
        ),
    ]
