# Generated by Django 2.1.2 on 2018-12-04 17:08

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('article', '0017_auto_20181123_0338'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='article',
            options={'ordering': ['-article_created'], 'verbose_name': 'Статья', 'verbose_name_plural': 'Статьи'},
        ),
        migrations.AlterModelOptions(
            name='comment',
            options={'ordering': ['-comment_created'], 'verbose_name': 'Комментарий', 'verbose_name_plural': 'Комментарии'},
        ),
    ]
