# Generated by Django 2.1.2 on 2018-12-04 17:21

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Programm',
            fields=[
                ('programm_title', models.CharField(max_length=80, primary_key=True, serialize=False, verbose_name='Название программы')),
            ],
            options={
                'verbose_name': 'Программа',
                'verbose_name_plural': 'Программы',
                'db_table': 'Programm',
            },
        ),
    ]
