# Generated by Django 2.1.2 on 2018-12-04 21:34

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('mainpage', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='ProComment',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment_text', models.TextField(verbose_name='Текст комментария')),
                ('comment_created', models.DateTimeField(auto_now_add=True, verbose_name='Добавлен')),
                ('comment_moderation', models.BooleanField(default=False, verbose_name='Модерация')),
                ('comment_programm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='mainpage.Programm', verbose_name='Программа')),
                ('comment_written_by', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор')),
            ],
            options={
                'verbose_name': 'Комментарий',
                'verbose_name_plural': 'Комментарии',
                'db_table': 'ProComment',
                'ordering': ['-comment_created'],
            },
        ),
    ]
